4 actualizar operarios con un servicio
AlexDiaz540/notifications-manager pull request #12
Opened 2024-07-22 11:46 UTC by AlexDiaz540

2024-07-23 08:37 UTC, AsierAlba10 requested changes
Topisimo Alex.
Algunas cosillas pero muy bien.
Los test revísalos con Iker.
Acostúmbrate a poner el titulo de la PR con un estándar. Nosotros lo ponemos así:
[<nº issue>] - <Título de la PR(Primera en mayuscula)>

2024-07-23 08:37 UTC, AsierAlba10 commented on notificationsManager/Operators/Commands/UpdateOperators.php
>  class UpdateOperators extends Command
Quizá sea mas verboso si lo renombramos a `UpdateOperatorsCommand`??

2024-07-23 08:37 UTC, AsierAlba10 commented on notificationsManager/Operators/Commands/UpdateOperators.php
>      public function handle(): int
Puedes pasarte el servicio directamente aquí. Sin necesidad del constructor

2024-07-23 08:37 UTC, AsierAlba10 commented on notificationsManager/Operators/UpdateOperatorsService.php
> +        private OperatorsRequestRepository $operatorsRequestRepository
OperatorsRequestRepository me genera dudas. Entiendo que quieres referirte a pedir los operadores a un api no??

Un repositorio es un concepto que usamos principalmente para persistir un dominio. Quizá tu te refieras más a `OperatorsApiDataSource`???

También solemos poner en el constructor las dependencias en el orden de como se usan.

2024-07-23 08:37 UTC, AsierAlba10 commented on notificationsManager/Operators/UpdateOperatorsService.php
> +                $operator = new Operator($operatorData);
Que te parece el tener que crear un Operador en cada data que tienes?? Pasar esta responsabilidad a otro lado??

Fíjate aquí:
$operatorsData = $this->operatorsRequestRepository->getOperators();

Que te parece si dentro de esa función mappeas los operadores y te devuelves un array de Operators? y aquí así solo tendrías que hacer el save

2024-07-23 08:37 UTC, AsierAlba10 commented on notificationsManager/Operators/UpdateOperatorsService.php
>          } catch (Exception $e) {
No usas $e

2024-07-23 08:37 UTC, AsierAlba10 commented on notificationsManager/Operators/UpdateOperatorsService.php
> +readonly class UpdateOperatorsService
No está testado??

2024-07-23 08:37 UTC, AsierAlba10 commented on notificationsManager/Operators/Repositories/OperatorsRequestRepository.php
> +interface OperatorsRequestRepository
Si cambias a data source igual esto no lo necesitas, no?

2024-07-23 08:37 UTC, AsierAlba10 commented on notificationsManager/Operators/Commands/UpdateOperators.php
>                  $this->error(json_encode(['message' => 'Failed to retrieve operators.'], JSON_THROW_ON_ERROR | JSON_UNESCAPED_UNICODE));
Puedes utilizar el mensaje de la exception?

2024-07-23 08:37 UTC, AsierAlba10 commented on notificationsManager/Operators/IlluminateOperatorsRequestRepository.php
> +    public function __construct()
Puedes poner en el constructor la dependencia

2024-07-23 08:37 UTC, AsierAlba10 commented on notificationsManager/Operators/IlluminateOperatorsRequestRepository.php
> +class IlluminateOperatorsRequestRepository implements OperatorsRequestRepository
Illuminate es el nombre de la librería. Creo que te ha liado el pensar que era un repositorio

2024-07-29 09:06 UTC, LeWricka requested changes
Hay cosas, dales una vuelta @igomezgo echa un ojo a la pr y a los comentarios,

2024-07-29 09:06 UTC, LeWricka commented on notificationsManager/Operators/Commands/UpdateOperatorsCommand.php
> +use Symfony\Component\HttpFoundation\Response as ResponseAlias;
No etniendo esta parte, por qué es necesario el as ResponseAlias?

2024-07-29 09:06 UTC, LeWricka commented on notificationsManager/Operators/Tests/Feature/UpdateOperatorsTest.php
> +        $operatorsData = [
Aquí ves algo que se puede mejorar?

2024-07-29 09:06 UTC, LeWricka commented on notificationsManager/Operators/Tests/Feature/UpdateOperatorsTest.php
> +        $expectedResponse = json_encode(['message' => 'Operators updated successfully.'], JSON_THROW_ON_ERROR);
Ajusta la AAA, a ver cómo sería

2024-07-29 09:06 UTC, LeWricka commented on notificationsManager/Operators/Tests/Feature/UpdateOperatorsTest.php
> +    public function updateMultipleOperators(): void
updatesMultipleOperators?

2024-07-29 09:06 UTC, LeWricka commented on notificationsManager/Operators/Tests/Feature/UpdateOperatorsTest.php
> +    public function updateOperatorsWithNoOperatorsReceived(): void
updatesOperatorsWithNoOperatorsReceived?

2024-07-29 09:06 UTC, LeWricka commented on notificationsManager/Operators/Tests/Feature/UpdateOperatorsTest.php
> +        $this->httpClient::fake([
La AAA

2024-07-29 09:06 UTC, LeWricka commented on notificationsManager/Operators/Tests/Feature/UpdateOperatorsTest.php
> +    public function updateOpertatorsWhenApiRequestFails(): void
Ídem para el resto de tests

2024-07-29 09:06 UTC, LeWricka commented on notificationsManager/Operators/Tests/Feature/UpdateOperatorsTest.php
>          $this->httpClient = new HttpClient();
Para plantearnos, ¿qué tests tiene sentido meter aquí?

2024-07-29 09:06 UTC, LeWricka commented on notificationsManager/Operators/Tests/Unit/OperatorRepositoryTest.php
> +        $operatorData = [
Esto te suena de algún otro sitio?

2024-07-29 09:06 UTC, LeWricka commented on notificationsManager/Operators/OperatorsApiDataSource.php
>          $this->httpClient::fake([
Es responsabilidad de este datasource hacer la llamada al fake?
Además, mira como en los tests, tiramos del http::fake, hay otra forma de implementar esta parte extrayendo el client, dale una vuelta y ajusta esto y el test

2024-07-29 09:06 UTC, LeWricka commented on notificationsManager/Operators/OperatorsApiDataSource.php
> +            $operatorsDate = $response->json();
Por qué operatorsDate y no operatorsData?

2024-07-29 09:06 UTC, LeWricka commented on notificationsManager/Operators/OperatorsApiDataSource.php
> +class OperatorsApiDataSource
Es esto un datasource o un repositorio?

2024-07-29 09:06 UTC, LeWricka commented on notificationsManager/Operators/Tests/Feature/UpdateOperatorsTest.php
>          $this->httpClient = new HttpClient();
Mira lo que te comento del client en el datasource

2024-07-29 09:06 UTC, LeWricka commented on notificationsManager/Operators/Tests/Unit/OperatorRequestRepositoryTest.php
> +    public function getSingleOperator(): void
getSingleOperator -> getsSingleOperator?

2024-07-29 09:06 UTC, LeWricka commented on notificationsManager/Operators/Tests/Unit/OperatorRequestRepositoryTest.php
> +    public function getSingleOperator(): void
y lo mismo en el resto de tests

2024-07-29 09:06 UTC, LeWricka commented on notificationsManager/Operators/Tests/Unit/OperatorRequestRepositoryTest.php
> +                'sequenceNumber' => 1510105,
Esto te suena también?

2024-07-29 09:06 UTC, LeWricka commented on notificationsManager/Operators/UpdateOperatorsService.php
> +        $operators = $this->operatorsApiDataSource->getOperators();
Esto déjalo para comentarlo, pero de quién es la responsabilidad de recibir los datos y convertirlos a operators?

2024-07-30 08:58 UTC, igomezgo commented on notificationsManager/Operators/Commands/UpdateOperatorsCommand.php
> +use Symfony\Component\HttpFoundation\Response as ResponseAlias;
Veo que esa librería es de Symfony. Si se quiere manejar los diferentes códigos de error, es decir, las excepciones (500, 400, 404, etc) se podría crear una clase HttpStatus, donde:

class HttpStatus {
    const HTTP_BAD_REQUEST = 400;
    const HTTP_INTERNAL_SERVER_ERROR = 500;
}

Y se llamaría a HttpStatus::HTTP_INTERNAL_SERVER_ERROR en vez de ResponseAlias.

Se podría lanzar un mensaje para que sea más legible, dónde ha pasado y qué ha pasado.

2024-08-06 06:08 UTC, merged